// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(chordsketchFFI)
import chordsketchFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_chordsketch_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_chordsketch_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureChordsketchFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt8: FfiConverterPrimitive {
    typealias FfiType = Int8
    typealias SwiftType = Int8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * Structured render result for text / HTML output.
 *
 * Returned by `parse_and_render_text_with_warnings` and
 * `parse_and_render_html_with_warnings`. Each warning is a
 * human-readable diagnostic string captured from the renderer
 * (e.g. "transpose offset ... clamped to ...").
 * A single `{define: <name> <raw>}` voicing entry passed to
 * `chord_diagram_svg_with_defines`. Mirrors the `(name, raw)`
 * tuple wasm / NAPI bindings accept.
 */
public struct ChordDefine: Equatable, Hashable {
    /**
     * Chord name (e.g. `"Gsus4"`, `"C#m7"`).
     */
    public var name: String
    /**
     * Raw directive body — what comes after `{define: <name> `.
     */
    public var raw: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Chord name (e.g. `"Gsus4"`, `"C#m7"`).
         */name: String, 
        /**
         * Raw directive body — what comes after `{define: <name> `.
         */raw: String) {
        self.name = name
        self.raw = raw
    }

    

    
}

#if compiler(>=6)
extension ChordDefine: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChordDefine: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChordDefine {
        return
            try ChordDefine(
                name: FfiConverterString.read(from: &buf), 
                raw: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ChordDefine, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.raw, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChordDefine_lift(_ buf: RustBuffer) throws -> ChordDefine {
    return try FfiConverterTypeChordDefine.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChordDefine_lower(_ value: ChordDefine) -> RustBuffer {
    return FfiConverterTypeChordDefine.lower(value)
}


/**
 * Structured result for ChordPro ↔ iReal Pro conversions
 * (#2067 Phase 1).
 *
 * `output` is the converted string (an `irealb://` URL or
 * rendered ChordPro text, depending on direction). `warnings`
 * holds human-readable descriptions of any information that
 * was dropped or approximated during the conversion. An empty
 * warning list indicates a clean (lossless-on-this-input)
 * conversion.
 */
public struct ConversionWithWarnings: Equatable, Hashable {
    /**
     * Converted output string.
     */
    public var output: String
    /**
     * Warnings captured during conversion (lossy drops,
     * approximated fields, unsupported features).
     */
    public var warnings: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Converted output string.
         */output: String, 
        /**
         * Warnings captured during conversion (lossy drops,
         * approximated fields, unsupported features).
         */warnings: [String]) {
        self.output = output
        self.warnings = warnings
    }

    

    
}

#if compiler(>=6)
extension ConversionWithWarnings: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConversionWithWarnings: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConversionWithWarnings {
        return
            try ConversionWithWarnings(
                output: FfiConverterString.read(from: &buf), 
                warnings: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ConversionWithWarnings, into buf: inout [UInt8]) {
        FfiConverterString.write(value.output, into: &buf)
        FfiConverterSequenceString.write(value.warnings, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversionWithWarnings_lift(_ buf: RustBuffer) throws -> ConversionWithWarnings {
    return try FfiConverterTypeConversionWithWarnings.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversionWithWarnings_lower(_ value: ConversionWithWarnings) -> RustBuffer {
    return FfiConverterTypeConversionWithWarnings.lower(value)
}


/**
 * Structured render result for PDF output.
 *
 * See `TextRenderWithWarnings` for the warnings contract.
 */
public struct PdfRenderWithWarnings: Equatable, Hashable {
    /**
     * Rendered PDF byte stream.
     */
    public var output: Data
    /**
     * Warnings captured during the render pass.
     */
    public var warnings: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Rendered PDF byte stream.
         */output: Data, 
        /**
         * Warnings captured during the render pass.
         */warnings: [String]) {
        self.output = output
        self.warnings = warnings
    }

    

    
}

#if compiler(>=6)
extension PdfRenderWithWarnings: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePdfRenderWithWarnings: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PdfRenderWithWarnings {
        return
            try PdfRenderWithWarnings(
                output: FfiConverterData.read(from: &buf), 
                warnings: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: PdfRenderWithWarnings, into buf: inout [UInt8]) {
        FfiConverterData.write(value.output, into: &buf)
        FfiConverterSequenceString.write(value.warnings, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePdfRenderWithWarnings_lift(_ buf: RustBuffer) throws -> PdfRenderWithWarnings {
    return try FfiConverterTypePdfRenderWithWarnings.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePdfRenderWithWarnings_lower(_ value: PdfRenderWithWarnings) -> RustBuffer {
    return FfiConverterTypePdfRenderWithWarnings.lower(value)
}


/**
 * One staff-placed chord tone returned by `chord_staff_notes()`.
 *
 * Mirrors the wasm `StaffNote` interface and the NAPI `StaffNote` object.
 */
public struct StaffNote: Equatable, Hashable {
    /**
     * Note letter the tone is spelled on, `"A"`–`"G"`.
     */
    public var letter: String
    /**
     * Signed accidental as a semitone offset on `letter`: `-1` flat,
     * `0` natural, `1` sharp, `±2` double, and `±3` for an
     * enharmonically-extreme root (e.g. `Cbdim7`). Consumers must handle
     * the full `-3..=3` range.
     */
    public var accidental: Int8
    /**
     * Scientific-pitch-notation octave (middle C = C4).
     */
    public var octave: Int8
    /**
     * Absolute MIDI note number, consistent with the spelling.
     */
    public var midi: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Note letter the tone is spelled on, `"A"`–`"G"`.
         */letter: String, 
        /**
         * Signed accidental as a semitone offset on `letter`: `-1` flat,
         * `0` natural, `1` sharp, `±2` double, and `±3` for an
         * enharmonically-extreme root (e.g. `Cbdim7`). Consumers must handle
         * the full `-3..=3` range.
         */accidental: Int8, 
        /**
         * Scientific-pitch-notation octave (middle C = C4).
         */octave: Int8, 
        /**
         * Absolute MIDI note number, consistent with the spelling.
         */midi: UInt8) {
        self.letter = letter
        self.accidental = accidental
        self.octave = octave
        self.midi = midi
    }

    

    
}

#if compiler(>=6)
extension StaffNote: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStaffNote: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StaffNote {
        return
            try StaffNote(
                letter: FfiConverterString.read(from: &buf), 
                accidental: FfiConverterInt8.read(from: &buf), 
                octave: FfiConverterInt8.read(from: &buf), 
                midi: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: StaffNote, into buf: inout [UInt8]) {
        FfiConverterString.write(value.letter, into: &buf)
        FfiConverterInt8.write(value.accidental, into: &buf)
        FfiConverterInt8.write(value.octave, into: &buf)
        FfiConverterUInt8.write(value.midi, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStaffNote_lift(_ buf: RustBuffer) throws -> StaffNote {
    return try FfiConverterTypeStaffNote.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStaffNote_lower(_ value: StaffNote) -> RustBuffer {
    return FfiConverterTypeStaffNote.lower(value)
}


public struct TextRenderWithWarnings: Equatable, Hashable {
    /**
     * Rendered text / HTML output.
     */
    public var output: String
    /**
     * Warnings captured during the render pass.
     */
    public var warnings: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Rendered text / HTML output.
         */output: String, 
        /**
         * Warnings captured during the render pass.
         */warnings: [String]) {
        self.output = output
        self.warnings = warnings
    }

    

    
}

#if compiler(>=6)
extension TextRenderWithWarnings: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTextRenderWithWarnings: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TextRenderWithWarnings {
        return
            try TextRenderWithWarnings(
                output: FfiConverterString.read(from: &buf), 
                warnings: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: TextRenderWithWarnings, into buf: inout [UInt8]) {
        FfiConverterString.write(value.output, into: &buf)
        FfiConverterSequenceString.write(value.warnings, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextRenderWithWarnings_lift(_ buf: RustBuffer) throws -> TextRenderWithWarnings {
    return try FfiConverterTypeTextRenderWithWarnings.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextRenderWithWarnings_lower(_ value: TextRenderWithWarnings) -> RustBuffer {
    return FfiConverterTypeTextRenderWithWarnings.lower(value)
}


/**
 * A single validation issue reported by `validate()`.
 *
 * Matches the NAPI `ValidationError` interface introduced in #1990 and
 * tracked for cross-binding consistency in #2009. Line and column are
 * one-based (editor diagnostic convention).
 */
public struct ValidationError: Equatable, Hashable {
    /**
     * One-based line number where the issue was detected.
     */
    public var line: UInt32
    /**
     * One-based column number where the issue was detected.
     */
    public var column: UInt32
    /**
     * Human-readable description of the issue.
     */
    public var message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * One-based line number where the issue was detected.
         */line: UInt32, 
        /**
         * One-based column number where the issue was detected.
         */column: UInt32, 
        /**
         * Human-readable description of the issue.
         */message: String) {
        self.line = line
        self.column = column
        self.message = message
    }

    

    
}

#if compiler(>=6)
extension ValidationError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeValidationError: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ValidationError {
        return
            try ValidationError(
                line: FfiConverterUInt32.read(from: &buf), 
                column: FfiConverterUInt32.read(from: &buf), 
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ValidationError, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.line, into: &buf)
        FfiConverterUInt32.write(value.column, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeValidationError_lift(_ buf: RustBuffer) throws -> ValidationError {
    return try FfiConverterTypeValidationError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeValidationError_lower(_ value: ValidationError) -> RustBuffer {
    return FfiConverterTypeValidationError.lower(value)
}


public 
enum ChordSketchError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * No songs found in the input.
     */
    case NoSongsFound
    /**
     * Invalid configuration string.
     */
    case InvalidConfig(reason: String
    )
    /**
     * A ChordPro ↔ iReal Pro conversion failed (#2067).
     * The contained `reason` is the parser or converter's
     * human-readable diagnostic.
     */
    case ConversionFailed(reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension ChordSketchError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChordSketchError: FfiConverterRustBuffer {
    typealias SwiftType = ChordSketchError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChordSketchError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NoSongsFound
        case 2: return .InvalidConfig(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .ConversionFailed(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChordSketchError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NoSongsFound:
            writeInt(&buf, Int32(1))
        
        
        case let .InvalidConfig(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .ConversionFailed(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChordSketchError_lift(_ buf: RustBuffer) throws -> ChordSketchError {
    return try FfiConverterTypeChordSketchError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChordSketchError_lower(_ value: ChordSketchError) -> RustBuffer {
    return FfiConverterTypeChordSketchError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt8: FfiConverterRustBuffer {
    typealias SwiftType = Int8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypeStaffNote: FfiConverterRustBuffer {
    typealias SwiftType = [StaffNote]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypeStaffNote.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypeStaffNote.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeChordDefine: FfiConverterRustBuffer {
    typealias SwiftType = [ChordDefine]

    public static func write(_ value: [ChordDefine], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChordDefine.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChordDefine] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChordDefine]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChordDefine.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeStaffNote: FfiConverterRustBuffer {
    typealias SwiftType = [StaffNote]

    public static func write(_ value: [StaffNote], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeStaffNote.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [StaffNote] {
        let len: Int32 = try readInt(&buf)
        var seq = [StaffNote]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeStaffNote.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeValidationError: FfiConverterRustBuffer {
    typealias SwiftType = [ValidationError]

    public static func write(_ value: [ValidationError], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeValidationError.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ValidationError] {
        let len: Int32 = try readInt(&buf)
        var seq = [ValidationError]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeValidationError.read(from: &buf))
        }
        return seq
    }
}
/**
 * Look up an SVG chord diagram for the given chord name and
 * instrument. Mirrors the WASM `chord_diagram_svg` export
 * added in #2164 and the NAPI `chordDiagramSvg` export
 * added in #2167.
 *
 * `instrument` accepts (case-insensitive): `"guitar"`,
 * `"ukulele"` (alias `"uke"`), or `"piano"` (aliases
 * `"keyboard"`, `"keys"`). `chord` is a standard ChordPro
 * chord name. Flat spellings are normalised to sharps via
 * the same path the core voicing-database lookup uses.
 *
 * Returns the inline SVG string, or `null` when the
 * built-in voicing database has no entry for this
 * `(chord, instrument)` pair. Throws `InvalidConfig` when
 * the instrument is unsupported.
 */
public func chordDiagramSvg(chord: String, instrument: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_chord_diagram_svg(
        FfiConverterString.lower(chord),
        FfiConverterString.lower(instrument),uniffiCallStatus
    )
})
}
/**
 * Like `chord_diagram_svg` but consults song-level `{define}`
 * voicings before falling back to the built-in voicing
 * database. `defines` is a list of `ChordDefine` records —
 * each carries a chord name and the raw `{define}` body
 * (e.g. `"base-fret 1 frets 3 3 0 0 1 3"`). Mirrors the
 * wasm `chordDiagramSvgWithDefines` and NAPI
 * `chordDiagramSvgWithDefines` exports so every binding
 * surface honours song-level `{define}` voicings the same way.
 */
public func chordDiagramSvgWithDefines(chord: String, instrument: String, defines: [ChordDefine])throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_chord_diagram_svg_with_defines(
        FfiConverterString.lower(chord),
        FfiConverterString.lower(instrument),
        FfiConverterSequenceTypeChordDefine.lower(defines),uniffiCallStatus
    )
})
}
/**
 * Combination of `chord_diagram_svg_with_defines` and
 * `chord_diagram_svg_with_orientation` (#2572).
 */
public func chordDiagramSvgWithDefinesOrientation(chord: String, instrument: String, defines: [ChordDefine], orientation: String?)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_chord_diagram_svg_with_defines_orientation(
        FfiConverterString.lower(chord),
        FfiConverterString.lower(instrument),
        FfiConverterSequenceTypeChordDefine.lower(defines),
        FfiConverterOptionString.lower(orientation),uniffiCallStatus
    )
})
}
/**
 * Like `chord_diagram_svg` but renders in the requested
 * orientation (#2572). `orientation` accepts `"vertical"`
 * (default) or `"horizontal"`. Horizontal mode is reader-view
 * only — see ADR-0026. `null` falls back to the default;
 * unrecognised strings fall back silently. Mirrors the wasm
 * `chordDiagramSvgWithOrientation` and NAPI
 * `chordDiagramSvgWithOrientation` exports so every binding
 * surface exposes the same orientation knob.
 */
public func chordDiagramSvgWithOrientation(chord: String, instrument: String, orientation: String?)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_chord_diagram_svg_with_orientation(
        FfiConverterString.lower(chord),
        FfiConverterString.lower(instrument),
        FfiConverterOptionString.lower(orientation),uniffiCallStatus
    )
})
}
/**
 * Constituent pitches of a chord as MIDI note numbers, for
 * driving an audio synth (#2650). Mirrors the wasm `chordPitches`
 * and NAPI `chordPitches` exports.
 *
 * Returns ascending, de-duplicated MIDI note numbers describing a
 * block voicing (root, third, fifth, plus any extension / altered
 * / added tones, with a slash bass dropped one octave below the
 * root), or `null` when `chord` is not parseable as a chord.
 */
public func chordPitches(chord: String) -> [UInt8]?  {
    return try!  FfiConverterOptionSequenceUInt8.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_chord_pitches(
        FfiConverterString.lower(chord),uniffiCallStatus
    )
})
}
/**
 * Constituent tones of a chord spelled for staff notation (#2695).
 * Mirrors the wasm `chordStaffNotes` and NAPI `chordStaffNotes`
 * exports.
 *
 * Returns the tones ascending by pitch (a slash bass sorts first),
 * or `null` when `chord` is not parseable as a chord. Each tone is
 * spelled diatonically from the chord's structure (e.g. `Ebm7` →
 * E♭ G♭ B♭ D♭, not D♯ F♯ A♯ C♯), so a renderer can place it on its
 * conventional staff line.
 */
public func chordStaffNotes(chord: String) -> [StaffNote]?  {
    return try!  FfiConverterOptionSequenceTypeStaffNote.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_chord_staff_notes(
        FfiConverterString.lower(chord),uniffiCallStatus
    )
})
}
/**
 * Convert a ChordPro source string into an `irealb://` URL
 * (#2067 Phase 1).
 *
 * Lossy: lyrics, fonts, colours, and capo are dropped; iReal
 * has no surface for them. Every drop surfaces in `warnings`
 * so callers never silently lose data.
 *
 * Throws `ConversionFailed` when the source is structurally
 * invalid for the iReal target format (e.g. a time signature
 * outside iReal's representable range).
 */
public func convertChordproToIrealb(input: String)throws  -> ConversionWithWarnings  {
    return try  FfiConverterTypeConversionWithWarnings_lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_convert_chordpro_to_irealb(
        FfiConverterString.lower(input),uniffiCallStatus
    )
})
}
/**
 * Convert an `irealb://` URL into rendered ChordPro text
 * (#2067 Phase 1).
 *
 * The output is the `chordsketch-render-text` rendering of the
 * converted song, not raw ChordPro source — there is no
 * ChordPro source emitter yet (tracked for a follow-up). Bar
 * boundaries (`|`) survive the conversion (asserted by the
 * per-binding tests); other surface details (chord lines,
 * section labels, etc.) are governed by `render-text`'s own
 * formatting contract.
 *
 * Throws `ConversionFailed` when the URL is not a valid
 * `irealb://` payload.
 */
public func convertIrealbToChordproText(input: String)throws  -> ConversionWithWarnings  {
    return try  FfiConverterTypeConversionWithWarnings_lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_convert_irealb_to_chordpro_text(
        FfiConverterString.lower(input),uniffiCallStatus
    )
})
}
/**
 * MIDI note numbers sounded by the chord diagram drawn for
 * (chord, instrument) — for auditioning a diagram as exactly the
 * shape it depicts, rather than the instrument-agnostic block
 * voicing `chord_pitches` returns from the chord name (#2736).
 * Mirrors the wasm `diagramPitches` and NAPI `diagramPitches`
 * exports.
 *
 * Fretted instruments ("guitar", "ukulele" / "uke") return one
 * pitch per non-muted string in string (strum) order, keeping
 * octave doublings; keyboard instruments ("piano", "keyboard",
 * "keys") return the highlighted keys. `defines` is the same
 * `ChordDefine` list `chord_diagram_svg_with_defines` consults
 * (ignored for keyboard). The accepted instrument set is kept in
 * lockstep with `chord_diagram_svg_with_defines`; anything outside
 * it (e.g. "charango", not drawn by the binding SVG path) returns
 * `null`. Also `null` when no diagram is available for the chord.
 */
public func diagramPitches(chord: String, instrument: String, defines: [ChordDefine]) -> [UInt8]?  {
    return try!  FfiConverterOptionSequenceUInt8.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_diagram_pitches(
        FfiConverterString.lower(chord),
        FfiConverterString.lower(instrument),
        FfiConverterSequenceTypeChordDefine.lower(defines),uniffiCallStatus
    )
})
}
/**
 * Ascending one-octave scale of a musical key as MIDI note
 * numbers, for auditioning the key by ear — the movable-do "do re
 * mi fa sol la ti do" (#2658). Mirrors the wasm `keyScalePitches`
 * and NAPI `keyScalePitches` exports.
 *
 * `key` is a ChordPro `{key}` value (`"C"`, `"Am"`, `"Bb"`,
 * `"F#m"`, …). Major keys yield the major scale; minor keys the
 * natural-minor scale. Returns eight ascending MIDI note numbers,
 * or `null` when `key` is not parseable as a chord.
 */
public func keyScalePitches(key: String) -> [UInt8]?  {
    return try!  FfiConverterOptionSequenceUInt8.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_key_scale_pitches(
        FfiConverterString.lower(key),uniffiCallStatus
    )
})
}
/**
 * Tonic triad of a musical key as MIDI note numbers — the "do mi
 * sol" chord strummed after the scale in a key audition (#2658).
 * Mirrors the wasm `keyTonicTriad` and NAPI `keyTonicTriad`
 * exports.
 *
 * Major keys yield a major triad, minor keys a minor triad. Any
 * extension on the key spelling (`"Cmaj7"`) is ignored — the key's
 * tonic chord is always a triad. Returns three ascending MIDI note
 * numbers, or `null` when `key` is not parseable as a chord.
 */
public func keyTonicTriad(key: String) -> [UInt8]?  {
    return try!  FfiConverterOptionSequenceUInt8.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_key_tonic_triad(
        FfiConverterString.lower(key),uniffiCallStatus
    )
})
}
/**
 * Parse ChordPro input and render as an HTML document.
 *
 * Parse warnings are silently discarded. Call `validate()` to retrieve
 * diagnostics if needed.
 */
public func parseAndRenderHtml(input: String, configJson: String?, transpose: Int8?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_and_render_html(
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(configJson),
        FfiConverterOptionInt8.lower(transpose),uniffiCallStatus
    )
})
}
/**
 * Parse ChordPro input and render as a body-only HTML fragment.
 *
 * Body-only counterpart to `parse_and_render_html`: returns just
 * the `<div class="song">...</div>` markup, with no `<!DOCTYPE>`,
 * `<html>`, `<head>`, `<title>`, or embedded `<style>`. Use this
 * from hosts that supply their own document envelope so the
 * chord-over-lyrics layout does not depend on HTML5's
 * nested-document recovery rules. Pair with `render_html_css()`
 * for the matching stylesheet (#2279).
 */
public func parseAndRenderHtmlBody(input: String, configJson: String?, transpose: Int8?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_and_render_html_body(
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(configJson),
        FfiConverterOptionInt8.lower(transpose),uniffiCallStatus
    )
})
}
/**
 * Parse ChordPro input, render as a body-only HTML fragment, and
 * return render warnings alongside the output.
 *
 * See `parse_and_render_html_body` for the body-only contract and
 * `parse_and_render_text_with_warnings` for the warnings contract.
 */
public func parseAndRenderHtmlBodyWithWarnings(input: String, configJson: String?, transpose: Int8?)throws  -> TextRenderWithWarnings  {
    return try  FfiConverterTypeTextRenderWithWarnings_lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_and_render_html_body_with_warnings(
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(configJson),
        FfiConverterOptionInt8.lower(transpose),uniffiCallStatus
    )
})
}
/**
 * Parse ChordPro input, render as an HTML document, and return
 * render warnings alongside the output.
 *
 * See `parse_and_render_text_with_warnings` for the warnings contract.
 */
public func parseAndRenderHtmlWithWarnings(input: String, configJson: String?, transpose: Int8?)throws  -> TextRenderWithWarnings  {
    return try  FfiConverterTypeTextRenderWithWarnings_lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_and_render_html_with_warnings(
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(configJson),
        FfiConverterOptionInt8.lower(transpose),uniffiCallStatus
    )
})
}
/**
 * Parse ChordPro input and render as a PDF document.
 *
 * Parse warnings are silently discarded. Call `validate()` to retrieve
 * diagnostics if needed.
 */
public func parseAndRenderPdf(input: String, configJson: String?, transpose: Int8?)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_and_render_pdf(
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(configJson),
        FfiConverterOptionInt8.lower(transpose),uniffiCallStatus
    )
})
}
/**
 * Parse ChordPro input, render as a PDF byte stream, and return
 * render warnings alongside the output.
 *
 * See `parse_and_render_text_with_warnings` for the warnings contract.
 */
public func parseAndRenderPdfWithWarnings(input: String, configJson: String?, transpose: Int8?)throws  -> PdfRenderWithWarnings  {
    return try  FfiConverterTypePdfRenderWithWarnings_lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_and_render_pdf_with_warnings(
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(configJson),
        FfiConverterOptionInt8.lower(transpose),uniffiCallStatus
    )
})
}
/**
 * Parse ChordPro input and render as plain text.
 *
 * Parse warnings are silently discarded. Call `validate()` to retrieve
 * diagnostics if needed.
 *
 * - `input`: ChordPro source text
 * - `config_json`: optional RRJSON configuration string or preset name
 *   (e.g., "guitar", "ukulele")
 * - `transpose`: semitone transposition offset (default 0)
 */
public func parseAndRenderText(input: String, configJson: String?, transpose: Int8?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_and_render_text(
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(configJson),
        FfiConverterOptionInt8.lower(transpose),uniffiCallStatus
    )
})
}
/**
 * Parse ChordPro input, render as plain text, and return render
 * warnings alongside the output instead of forwarding them to
 * stderr.
 *
 * See `parse_and_render_text` for the parameter contract. Use this
 * variant when the host binding needs to surface warnings in a UI
 * (see #1827).
 */
public func parseAndRenderTextWithWarnings(input: String, configJson: String?, transpose: Int8?)throws  -> TextRenderWithWarnings  {
    return try  FfiConverterTypeTextRenderWithWarnings_lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_and_render_text_with_warnings(
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(configJson),
        FfiConverterOptionInt8.lower(transpose),uniffiCallStatus
    )
})
}
/**
 * Parse an `irealb://` URL into an AST-shaped JSON string
 * (#2067 Phase 2b).
 *
 * The returned JSON object mirrors the `IrealSong` AST in
 * `chordsketch-ireal`. Pair with `serialize_irealb` for the
 * inverse direction. Field additions are non-breaking; field
 * removals or renames require a major version bump.
 *
 * Throws `ConversionFailed` when the URL is not a valid
 * `irealb://` payload.
 */
public func parseIrealb(input: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_parse_irealb(
        FfiConverterString.lower(input),uniffiCallStatus
    )
})
}
/**
 * Returns the canonical chord-over-lyrics CSS that
 * `parse_and_render_html` embeds inside `<style>`.
 *
 * Pair with `parse_and_render_html_body` when the consumer is
 * supplying its own document envelope (#2279).
 */
public func renderHtmlCss() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_render_html_css(uniffiCallStatus
    )
})
}
/**
 * Variant of `render_html_css` that honours `settings.wraplines`
 * from the supplied config (R6.100.0). When `wraplines` is false,
 * the `.line` rule emits `flex-wrap: nowrap`.
 */
public func renderHtmlCssWithConfigJson(configJson: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_render_html_css_with_config_json(
        FfiConverterOptionString.lower(configJson),uniffiCallStatus
    )
})
}
/**
 * Render an `irealb://` URL as a single-page A4 PDF document
 * (#2067 Phase 2c).
 *
 * Wraps `chordsketch-render-ireal::pdf::render_pdf` with the
 * default `PdfOptions`. The chart is embedded as vector
 * content, so the PDF is resolution-independent.
 *
 * Throws `ConversionFailed` when the URL is not a valid
 * `irealb://` payload, or when the underlying converter fails.
 */
public func renderIrealPdf(input: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_render_ireal_pdf(
        FfiConverterString.lower(input),uniffiCallStatus
    )
})
}
/**
 * Render an `irealb://` URL as an iReal Pro-style PNG image
 * (#2067 Phase 2c).
 *
 * Wraps `chordsketch-render-ireal::png::render_png` with the
 * default `PngOptions` (300 DPI, A4-equivalent canvas). The
 * returned byte stream is a complete PNG file.
 *
 * Throws `ConversionFailed` when the URL is not a valid
 * `irealb://` payload, or when the underlying rasteriser fails.
 */
public func renderIrealPng(input: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_render_ireal_png(
        FfiConverterString.lower(input),uniffiCallStatus
    )
})
}
/**
 * Render an `irealb://` URL as an iReal Pro-style SVG chart
 * (#2067 Phase 2a).
 *
 * Wraps `chordsketch-render-ireal::render_svg` with default
 * `RenderOptions`. The SVG output is a complete, self-contained
 * `<svg>` document that can be embedded in HTML, opened in a
 * browser, or further rasterised via `resvg` / `svg2pdf`.
 *
 * Throws `ConversionFailed` when the URL is not a valid
 * `irealb://` payload. Successful renders never fail — the
 * SVG renderer is total once it has a parsed song.
 */
public func renderIrealSvg(input: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_render_ireal_svg(
        FfiConverterString.lower(input),uniffiCallStatus
    )
})
}
/**
 * Serialize an AST-shaped JSON string into an `irealb://` URL
 * (#2067 Phase 2b).
 *
 * The input must match the JSON shape produced by
 * `parse_irealb`. Round-trip identity is guaranteed for any
 * JSON `parse_irealb` produced on the same library version.
 *
 * Throws `ConversionFailed` when the input is not valid JSON
 * or does not match the AST shape (missing required fields,
 * out-of-range values).
 */
public func serializeIrealb(input: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChordSketchError_lift) {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_serialize_irealb(
        FfiConverterString.lower(input),uniffiCallStatus
    )
})
}
/**
 * Validate ChordPro input and return any parse errors as structured
 * records. Returns an empty list if the input is valid.
 *
 * Call this before or after rendering to surface parse diagnostics
 * that the render functions silently discard. Each entry carries a
 * one-based `line`, one-based `column`, and a human-readable message.
 */
public func validate(input: String) -> [ValidationError]  {
    return try!  FfiConverterSequenceTypeValidationError.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_validate(
        FfiConverterString.lower(input),uniffiCallStatus
    )
})
}
/**
 * Return the ChordSketch library version.
 */
public func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_chordsketch_ffi_fn_func_version(uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_chordsketch_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_chord_diagram_svg() != 10230) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_chord_diagram_svg_with_defines() != 51126) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_chord_diagram_svg_with_defines_orientation() != 26183) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_chord_diagram_svg_with_orientation() != 58122) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_chord_pitches() != 61756) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_chord_staff_notes() != 21004) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_convert_chordpro_to_irealb() != 6737) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_convert_irealb_to_chordpro_text() != 44836) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_diagram_pitches() != 42594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_key_scale_pitches() != 31174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_key_tonic_triad() != 53510) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_and_render_html() != 14717) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_and_render_html_body() != 4358) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_and_render_html_body_with_warnings() != 21411) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_and_render_html_with_warnings() != 4339) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_and_render_pdf() != 14533) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_and_render_pdf_with_warnings() != 32896) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_and_render_text() != 52565) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_and_render_text_with_warnings() != 32765) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_parse_irealb() != 9812) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_render_html_css() != 48656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_render_html_css_with_config_json() != 11415) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_render_ireal_pdf() != 31257) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_render_ireal_png() != 58887) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_render_ireal_svg() != 13113) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_serialize_irealb() != 4600) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_validate() != 3675) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chordsketch_ffi_checksum_func_version() != 64540) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureChordsketchFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all