[package]
name = "chordsketch-import-gp"
version = "0.7.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["guitar-pro", "gp5", "chordpro", "music", "converter"]
categories = ["parser-implementations", "text-processing"]
readme = "README.md"
description = "Guitar Pro 5 (.gp5) to ChordPro importer"

[dependencies]
chordsketch-chordpro = { version = "0.7.0", path = "../chordpro" }
chordsketch-convert = { version = "0.7.0", path = "../convert" }
