name: Bug
description: Something isn't working
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's broken?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
