// This file is a placeholder. The actual Kotlin bindings are generated by
// UniFFI at build time via the CI workflow and placed in this directory.
//
// For local development, generate bindings with:
//   cargo run -p chordsketch-ffi --bin uniffi-bindgen generate \
//     --library target/debug/libchordsketch_ffi.so \
//     --language kotlin \
//     --out-dir packages/kotlin/lib/src/main/kotlin/
