#!/usr/bin/env python3
"""Tests for `macports-regen-cargo-crates.py`.

The pure functions (`portfile_tag`, `parse_cargo_lock`, `render_block`,
`replace_block_in_portfile`, plus the `from_ref` validation in
`read_cargo_lock`) are unit-tested against synthetic fixtures so the
suite is independent of the real Portfile / Cargo.lock.

Tests intentionally do NOT exercise the `git show` subprocess path —
that would couple the suite to the host's git history. The `from_ref`
validation guard (refuses values starting with `-`) IS covered because
it short-circuits before any subprocess call.
"""
from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))

_spec = importlib.util.spec_from_file_location(
    "macports_regen_cargo_crates",
    SCRIPTS_DIR / "macports-regen-cargo-crates.py",
)
assert _spec is not None and _spec.loader is not None
mod = importlib.util.module_from_spec(_spec)
sys.modules["macports_regen_cargo_crates"] = mod
_spec.loader.exec_module(mod)


PORTFILE_FIXTURE = """\
PortSystem 1.0
PortGroup github 1.0
PortGroup cargo 1.0

github.setup        koedame chordsketch 0.3.0 v
revision            0
categories          textproc music
license             MIT

cargo.crates \\
    aaa 1.0.0 0000000000000000000000000000000000000000000000000000000000000001 \\
    bbb 2.0.0 0000000000000000000000000000000000000000000000000000000000000002

build.dir ${worksrcpath}
"""


CARGO_LOCK_FIXTURE = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "alpha"
version = "1.2.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaa000000000000000000000000000000000000000000000000000000000001"

[[package]]
name = "beta"
version = "0.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbbb000000000000000000000000000000000000000000000000000000000002"

[[package]]
name = "workspace-local-crate"
version = "0.1.0"
"""


class PortfileTagTests(unittest.TestCase):
    def test_resolves_version_from_github_setup(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            portfile = root / "packaging" / "macports" / "Portfile"
            portfile.parent.mkdir(parents=True)
            portfile.write_text(PORTFILE_FIXTURE, encoding="utf-8")
            mod.REPO_ROOT = root
            mod.PORTFILE = portfile
            self.assertEqual(mod.portfile_tag(), "v0.3.0")

    def test_rejects_portfile_without_github_setup(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            portfile = root / "packaging" / "macports" / "Portfile"
            portfile.parent.mkdir(parents=True)
            portfile.write_text("PortSystem 1.0\n", encoding="utf-8")
            mod.REPO_ROOT = root
            mod.PORTFILE = portfile
            with self.assertRaises(SystemExit):
                mod.portfile_tag()

    def test_rejects_dash_prefixed_version(self) -> None:
        # `\S+` would have accepted `--upload-pack=evil` or similar;
        # the tightened regex captures only `[0-9][0-9A-Za-z.+-]*`.
        bad = PORTFILE_FIXTURE.replace(
            "github.setup        koedame chordsketch 0.3.0 v",
            "github.setup        koedame chordsketch -evil v",
        )
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            portfile = root / "packaging" / "macports" / "Portfile"
            portfile.parent.mkdir(parents=True)
            portfile.write_text(bad, encoding="utf-8")
            mod.REPO_ROOT = root
            mod.PORTFILE = portfile
            with self.assertRaises(SystemExit):
                mod.portfile_tag()


class ParseCargoLockTests(unittest.TestCase):
    def test_excludes_workspace_local_crates(self) -> None:
        crates = mod.parse_cargo_lock(CARGO_LOCK_FIXTURE)
        names = [c[0] for c in crates]
        # `workspace-local-crate` has no `checksum =` line and is
        # excluded by design — the cargo portgroup expects only
        # registry crates in `cargo.crates`.
        self.assertEqual(names, ["alpha", "beta"])

    def test_returns_sorted_by_name(self) -> None:
        out_of_order = """
[[package]]
name = "zeta"
version = "1.0.0"
checksum = "ffff000000000000000000000000000000000000000000000000000000000001"

[[package]]
name = "alpha"
version = "1.0.0"
checksum = "aaaa000000000000000000000000000000000000000000000000000000000001"
"""
        crates = mod.parse_cargo_lock(out_of_order)
        self.assertEqual([c[0] for c in crates], ["alpha", "zeta"])

    def test_captures_version_and_checksum(self) -> None:
        crates = mod.parse_cargo_lock(CARGO_LOCK_FIXTURE)
        self.assertEqual(
            crates[0],
            ("alpha", "1.2.3",
             "aaaa000000000000000000000000000000000000000000000000000000000001"),
        )


class RenderBlockTests(unittest.TestCase):
    def test_empty_input_returns_bare_directive(self) -> None:
        self.assertEqual(mod.render_block([]), "cargo.crates\n")

    def test_single_crate_has_no_trailing_backslash(self) -> None:
        block = mod.render_block([("foo", "1.0.0", "abc123")])
        self.assertEqual(block, "cargo.crates \\\n    foo 1.0.0 abc123\n")

    def test_multi_crate_continues_with_backslashes(self) -> None:
        block = mod.render_block([
            ("alpha", "1.0.0", "aaa"),
            ("beta", "2.0.0", "bbb"),
        ])
        self.assertEqual(
            block,
            "cargo.crates \\\n"
            "    alpha 1.0.0 aaa \\\n"
            "    beta 2.0.0 bbb\n",
        )


class ReplaceBlockTests(unittest.TestCase):
    def test_replaces_only_cargo_crates_region(self) -> None:
        new_block = "cargo.crates \\\n    new 9.9.9 deadbeef\n"
        result = mod.replace_block_in_portfile(PORTFILE_FIXTURE, new_block)
        self.assertIn("github.setup        koedame chordsketch 0.3.0 v",
                      result)
        self.assertIn("    new 9.9.9 deadbeef", result)
        self.assertNotIn("aaa 1.0.0", result)
        # `build.dir` line after the block must survive.
        self.assertIn("build.dir ${worksrcpath}", result)

    def test_raises_when_no_cargo_crates_line(self) -> None:
        with self.assertRaises(SystemExit):
            mod.replace_block_in_portfile(
                "PortSystem 1.0\n",
                "cargo.crates\n",
            )

    def test_raises_when_block_lacks_terminating_blank_line(self) -> None:
        # Build a Portfile where `cargo.crates` is the very last
        # content with no trailing blank line.
        bad = "PortSystem 1.0\n\ncargo.crates \\\n    foo 1.0.0 abc"
        with self.assertRaises(SystemExit):
            mod.replace_block_in_portfile(bad, "cargo.crates\n")


class ReadCargoLockGuardTests(unittest.TestCase):
    def test_rejects_dash_prefixed_ref_before_subprocess(self) -> None:
        # Must short-circuit before any `git show` invocation —
        # otherwise the test would depend on git being on PATH.
        with self.assertRaises(SystemExit) as cm:
            mod.read_cargo_lock("--upload-pack=evil")
        self.assertIn("refusing to use git ref starting with '-'",
                      str(cm.exception))

    def test_rejects_simple_dash_prefix(self) -> None:
        with self.assertRaises(SystemExit):
            mod.read_cargo_lock("-foo")


if __name__ == "__main__":
    unittest.main()
