#!/usr/bin/env python3
"""Tests for `macports-regen-cargo-crates.py`.

The pure functions (`portfile_tag`, `parse_cargo_lock`, `render_block`,
`replace_block_in_portfile`, plus the `from_ref` validation in
`read_cargo_lock`) are unit-tested against synthetic fixtures so the
suite is independent of the real Portfile / Cargo.lock.

Tests intentionally do NOT exercise the `git show` subprocess path
end-to-end — that would couple the suite to the host's git history.
The `from_ref` validation guard (refuses values starting with `-`)
IS covered because it short-circuits before any subprocess call. The
`GitRefMissingError` classification path is covered by patching
`subprocess.run` to return a synthesised CalledProcessError, and
`cmd_check`'s release-cut fallback is covered by patching
`read_cargo_lock` itself.
"""
from __future__ import annotations

import importlib.util
import subprocess
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))

_spec = importlib.util.spec_from_file_location(
    "macports_regen_cargo_crates",
    SCRIPTS_DIR / "macports-regen-cargo-crates.py",
)
assert _spec is not None and _spec.loader is not None
mod = importlib.util.module_from_spec(_spec)
sys.modules["macports_regen_cargo_crates"] = mod
_spec.loader.exec_module(mod)


PORTFILE_FIXTURE = """\
PortSystem 1.0
PortGroup github 1.0
PortGroup cargo 1.0

github.setup        koedame chordsketch 0.3.0 v
revision            0
categories          textproc music
license             MIT

cargo.crates \\
    aaa 1.0.0 0000000000000000000000000000000000000000000000000000000000000001 \\
    bbb 2.0.0 0000000000000000000000000000000000000000000000000000000000000002

build.dir ${worksrcpath}
"""


CARGO_LOCK_FIXTURE = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "alpha"
version = "1.2.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaa000000000000000000000000000000000000000000000000000000000001"

[[package]]
name = "beta"
version = "0.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbbb000000000000000000000000000000000000000000000000000000000002"

[[package]]
name = "workspace-local-crate"
version = "0.1.0"
"""


class PortfileTagTests(unittest.TestCase):
    def test_resolves_version_from_github_setup(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            portfile = root / "packaging" / "macports" / "Portfile"
            portfile.parent.mkdir(parents=True)
            portfile.write_text(PORTFILE_FIXTURE, encoding="utf-8")
            mod.REPO_ROOT = root
            mod.PORTFILE = portfile
            self.assertEqual(mod.portfile_tag(), "v0.3.0")

    def test_rejects_portfile_without_github_setup(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            portfile = root / "packaging" / "macports" / "Portfile"
            portfile.parent.mkdir(parents=True)
            portfile.write_text("PortSystem 1.0\n", encoding="utf-8")
            mod.REPO_ROOT = root
            mod.PORTFILE = portfile
            with self.assertRaises(SystemExit):
                mod.portfile_tag()

    def test_rejects_dash_prefixed_version(self) -> None:
        # `\S+` would have accepted `--upload-pack=evil` or similar;
        # the tightened regex captures only `[0-9][0-9A-Za-z.+-]*`.
        bad = PORTFILE_FIXTURE.replace(
            "github.setup        koedame chordsketch 0.3.0 v",
            "github.setup        koedame chordsketch -evil v",
        )
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            portfile = root / "packaging" / "macports" / "Portfile"
            portfile.parent.mkdir(parents=True)
            portfile.write_text(bad, encoding="utf-8")
            mod.REPO_ROOT = root
            mod.PORTFILE = portfile
            with self.assertRaises(SystemExit):
                mod.portfile_tag()


class ParseCargoLockTests(unittest.TestCase):
    def test_excludes_workspace_local_crates(self) -> None:
        crates = mod.parse_cargo_lock(CARGO_LOCK_FIXTURE)
        names = [c[0] for c in crates]
        # `workspace-local-crate` has no `checksum =` line and is
        # excluded by design — the cargo portgroup expects only
        # registry crates in `cargo.crates`.
        self.assertEqual(names, ["alpha", "beta"])

    def test_returns_sorted_by_name(self) -> None:
        out_of_order = """
[[package]]
name = "zeta"
version = "1.0.0"
checksum = "ffff000000000000000000000000000000000000000000000000000000000001"

[[package]]
name = "alpha"
version = "1.0.0"
checksum = "aaaa000000000000000000000000000000000000000000000000000000000001"
"""
        crates = mod.parse_cargo_lock(out_of_order)
        self.assertEqual([c[0] for c in crates], ["alpha", "zeta"])

    def test_captures_version_and_checksum(self) -> None:
        crates = mod.parse_cargo_lock(CARGO_LOCK_FIXTURE)
        self.assertEqual(
            crates[0],
            ("alpha", "1.2.3",
             "aaaa000000000000000000000000000000000000000000000000000000000001"),
        )


class RenderBlockTests(unittest.TestCase):
    def test_empty_input_returns_bare_directive(self) -> None:
        self.assertEqual(mod.render_block([]), "cargo.crates\n")

    def test_single_crate_has_no_trailing_backslash(self) -> None:
        block = mod.render_block([("foo", "1.0.0", "abc123")])
        self.assertEqual(block, "cargo.crates \\\n    foo 1.0.0 abc123\n")

    def test_multi_crate_continues_with_backslashes(self) -> None:
        block = mod.render_block([
            ("alpha", "1.0.0", "aaa"),
            ("beta", "2.0.0", "bbb"),
        ])
        self.assertEqual(
            block,
            "cargo.crates \\\n"
            "    alpha 1.0.0 aaa \\\n"
            "    beta 2.0.0 bbb\n",
        )


class ReplaceBlockTests(unittest.TestCase):
    def test_replaces_only_cargo_crates_region(self) -> None:
        new_block = "cargo.crates \\\n    new 9.9.9 deadbeef\n"
        result = mod.replace_block_in_portfile(PORTFILE_FIXTURE, new_block)
        self.assertIn("github.setup        koedame chordsketch 0.3.0 v",
                      result)
        self.assertIn("    new 9.9.9 deadbeef", result)
        self.assertNotIn("aaa 1.0.0", result)
        # `build.dir` line after the block must survive.
        self.assertIn("build.dir ${worksrcpath}", result)

    def test_raises_when_no_cargo_crates_line(self) -> None:
        with self.assertRaises(SystemExit):
            mod.replace_block_in_portfile(
                "PortSystem 1.0\n",
                "cargo.crates\n",
            )

    def test_raises_when_block_lacks_terminating_blank_line(self) -> None:
        # Build a Portfile where `cargo.crates` is the very last
        # content with no trailing blank line.
        bad = "PortSystem 1.0\n\ncargo.crates \\\n    foo 1.0.0 abc"
        with self.assertRaises(SystemExit):
            mod.replace_block_in_portfile(bad, "cargo.crates\n")


class ReadCargoLockGuardTests(unittest.TestCase):
    def test_rejects_dash_prefixed_ref_before_subprocess(self) -> None:
        # Must short-circuit before any `git show` invocation —
        # otherwise the test would depend on git being on PATH.
        with self.assertRaises(SystemExit) as cm:
            mod.read_cargo_lock("--upload-pack=evil")
        self.assertIn("refusing to use git ref starting with '-'",
                      str(cm.exception))

    def test_rejects_simple_dash_prefix(self) -> None:
        with self.assertRaises(SystemExit):
            mod.read_cargo_lock("-foo")


def _make_called_process_error(stderr: str) -> subprocess.CalledProcessError:
    err = subprocess.CalledProcessError(returncode=128, cmd=["git", "show"])
    err.stderr = stderr
    return err


class ReadCargoLockGitRefMissingTests(unittest.TestCase):
    """Verify the `GitRefMissingError` classification."""

    def test_invalid_object_name_raises_GitRefMissingError(self) -> None:
        # The exact stderr `git show` emits when a ref does not exist.
        err = _make_called_process_error(
            "fatal: invalid object name 'v9.9.9'."
        )
        with patch.object(mod.subprocess, "run", side_effect=err):
            with self.assertRaises(mod.GitRefMissingError) as cm:
                mod.read_cargo_lock("v9.9.9")
        self.assertEqual(cm.exception.ref, "v9.9.9")
        self.assertIn("invalid object name", cm.exception.stderr)

    def test_bad_revision_also_classified_as_GitRefMissingError(self) -> None:
        # Some git versions emit "bad revision" instead. Both indicate
        # the ref is unreachable.
        err = _make_called_process_error("fatal: bad revision 'vNOPE'.")
        with patch.object(mod.subprocess, "run", side_effect=err):
            with self.assertRaises(mod.GitRefMissingError):
                mod.read_cargo_lock("vNOPE")

    def test_unrelated_git_error_still_raises_SystemExit(self) -> None:
        # E.g., the ref exists but has no `Cargo.lock` at that revision.
        err = _make_called_process_error(
            "fatal: path 'Cargo.lock' does not exist in 'v0.0.1'"
        )
        with patch.object(mod.subprocess, "run", side_effect=err):
            with self.assertRaises(SystemExit) as cm:
                mod.read_cargo_lock("v0.0.1")
        # Must NOT degrade to GitRefMissingError — that would silently
        # mask a real "Cargo.lock missing" defect on a tagged release.
        self.assertNotIsInstance(cm.exception, mod.GitRefMissingError)


def _matching_portfile() -> str:
    """Portfile whose cargo.crates block matches CARGO_LOCK_FIXTURE exactly."""
    return (
        "PortSystem 1.0\n"
        "PortGroup github 1.0\n"
        "PortGroup cargo 1.0\n"
        "\n"
        "github.setup        koedame chordsketch 0.5.0 v\n"
        "revision            0\n"
        "categories          textproc music\n"
        "license             MIT\n"
        "\n"
        + mod.render_block(mod.parse_cargo_lock(CARGO_LOCK_FIXTURE))
        + "\n"
        "build.dir ${worksrcpath}\n"
    )


class CmdCheckFallbackTests(unittest.TestCase):
    """`cmd_check` graceful fallback during the release-cut window (#2413)."""

    def _setup_portfile(self, tmp: str, body: str) -> Path:
        root = Path(tmp)
        portfile = root / "packaging" / "macports" / "Portfile"
        portfile.parent.mkdir(parents=True)
        portfile.write_text(body, encoding="utf-8")
        mod.REPO_ROOT = root
        mod.PORTFILE = portfile
        return portfile

    def test_fallback_passes_when_block_matches_HEAD(self) -> None:
        # Simulate a release-cut PR: Portfile points at v0.5.0 (not yet
        # tagged) but the cargo.crates block was regenerated against
        # HEAD's Cargo.lock, so the fallback comparison succeeds.
        with TemporaryDirectory() as tmp:
            self._setup_portfile(tmp, _matching_portfile())

            def _fake_read(ref: str) -> str:
                if ref == "v0.5.0":
                    raise mod.GitRefMissingError(
                        "v0.5.0", "fatal: invalid object name 'v0.5.0'."
                    )
                if ref == "HEAD":
                    return CARGO_LOCK_FIXTURE
                self.fail(f"unexpected ref: {ref}")

            with patch.object(mod, "read_cargo_lock", side_effect=_fake_read):
                rc = mod.cmd_check("v0.5.0", allow_tag_fallback=True)
            self.assertEqual(rc, 0)

    def test_fallback_disabled_returns_1_on_missing_ref(self) -> None:
        # An explicit `--from-ref` that does not exist must NOT silently
        # fall back to HEAD — explicit user intent is preserved.
        with TemporaryDirectory() as tmp:
            self._setup_portfile(tmp, _matching_portfile())

            def _fake_read(ref: str) -> str:
                raise mod.GitRefMissingError(
                    ref, f"fatal: invalid object name '{ref}'."
                )

            with patch.object(mod, "read_cargo_lock", side_effect=_fake_read):
                rc = mod.cmd_check("vNOPE", allow_tag_fallback=False)
            self.assertEqual(rc, 1)

    def test_fallback_still_reports_drift(self) -> None:
        # When the fallback comparison surfaces actual drift between
        # Portfile and HEAD, cmd_check must still report it (return 1)
        # — the fallback is a venue change, not a free pass.
        with TemporaryDirectory() as tmp:
            # Portfile has a cargo.crates block that does NOT match HEAD's
            # Cargo.lock contents.
            stale_portfile = (
                "PortSystem 1.0\n"
                "PortGroup github 1.0\n"
                "PortGroup cargo 1.0\n"
                "\n"
                "github.setup        koedame chordsketch 0.5.0 v\n"
                "revision            0\n"
                "license             MIT\n"
                "\n"
                "cargo.crates \\\n"
                "    stale 0.0.0 stalestalestalestalestalestalestalestalestalestalestalestale\n"
                "\n"
                "build.dir ${worksrcpath}\n"
            )
            self._setup_portfile(tmp, stale_portfile)

            def _fake_read(ref: str) -> str:
                if ref == "v0.5.0":
                    raise mod.GitRefMissingError(
                        "v0.5.0", "fatal: invalid object name 'v0.5.0'."
                    )
                return CARGO_LOCK_FIXTURE

            with patch.object(mod, "read_cargo_lock", side_effect=_fake_read):
                rc = mod.cmd_check("v0.5.0", allow_tag_fallback=True)
            self.assertEqual(rc, 1)


if __name__ == "__main__":
    unittest.main()
