/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__empty_line = 1,
  sym_comment = 2,
  anon_sym_LBRACE = 3,
  aux_sym_block_start_directive_token1 = 4,
  aux_sym_block_start_directive_token2 = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LF = 7,
  aux_sym_block_end_directive_token1 = 8,
  aux_sym_block_content_token1 = 9,
  sym_directive_name = 10,
  sym_directive_value = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  sym_chord_name = 14,
  sym_lyrics = 15,
  sym_source_file = 16,
  sym__line = 17,
  sym_delegate_block = 18,
  sym_block_start_directive = 19,
  sym_block_end_directive = 20,
  sym_block_content = 21,
  sym_directive = 22,
  sym_content_line = 23,
  sym_chord = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_block_content_repeat1 = 26,
  aux_sym_content_line_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__empty_line] = "_empty_line",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [aux_sym_block_start_directive_token1] = "directive_name",
  [aux_sym_block_start_directive_token2] = "block_start_directive_token2",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LF] = "\n",
  [aux_sym_block_end_directive_token1] = "directive_name",
  [aux_sym_block_content_token1] = "block_content_token1",
  [sym_directive_name] = "directive_name",
  [sym_directive_value] = "directive_value",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_chord_name] = "chord_name",
  [sym_lyrics] = "lyrics",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_delegate_block] = "delegate_block",
  [sym_block_start_directive] = "block_start_directive",
  [sym_block_end_directive] = "block_end_directive",
  [sym_block_content] = "block_content",
  [sym_directive] = "directive",
  [sym_content_line] = "content_line",
  [sym_chord] = "chord",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_content_repeat1] = "block_content_repeat1",
  [aux_sym_content_line_repeat1] = "content_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__empty_line] = sym__empty_line,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_block_start_directive_token1] = sym_directive_name,
  [aux_sym_block_start_directive_token2] = aux_sym_block_start_directive_token2,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_block_end_directive_token1] = sym_directive_name,
  [aux_sym_block_content_token1] = aux_sym_block_content_token1,
  [sym_directive_name] = sym_directive_name,
  [sym_directive_value] = sym_directive_value,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_chord_name] = sym_chord_name,
  [sym_lyrics] = sym_lyrics,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_delegate_block] = sym_delegate_block,
  [sym_block_start_directive] = sym_block_start_directive,
  [sym_block_end_directive] = sym_block_end_directive,
  [sym_block_content] = sym_block_content,
  [sym_directive] = sym_directive,
  [sym_content_line] = sym_content_line,
  [sym_chord] = sym_chord,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_content_repeat1] = aux_sym_block_content_repeat1,
  [aux_sym_content_line_repeat1] = aux_sym_content_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__empty_line] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_start_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_start_directive_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_end_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_chord_name] = {
    .visible = true,
    .named = true,
  },
  [sym_lyrics] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_delegate_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_start_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_block_end_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_chord] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') SKIP(15);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 's') ADVANCE(40);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == ' ' ||
          lookahead == ':') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\r') SKIP(4);
      if (lookahead == 's') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == '\r') SKIP(5);
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '\r') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 7:
      if (lookahead == '\r') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(50);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == '_') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 14:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 15:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') SKIP(15);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 's') ADVANCE(40);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(51);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(52);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(51);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(52);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__empty_line);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_block_start_directive_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_block_start_directive_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_block_end_directive_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_block_content_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '_') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '_') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '_') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'a') ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'd') ADVANCE(28);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'f') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'n') ADVANCE(33);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'o') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'o') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'r') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_directive_value);
      if (lookahead == '\r') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_directive_value);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_chord_name);
      if (lookahead == '\r') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_chord_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_lyrics);
      if (lookahead == '\r') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_lyrics);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__empty_line] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [aux_sym_block_start_directive_token1] = ACTIONS(1),
    [aux_sym_block_start_directive_token2] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_block_end_directive_token1] = ACTIONS(1),
    [sym_directive_name] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym__line] = STATE(2),
    [sym_delegate_block] = STATE(2),
    [sym_block_start_directive] = STATE(16),
    [sym_directive] = STATE(2),
    [sym_content_line] = STATE(2),
    [sym_chord] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_content_line_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__empty_line] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_lyrics] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_lyrics,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym_block_start_directive,
    ACTIONS(15), 2,
      sym__empty_line,
      sym_comment,
    STATE(4), 2,
      sym_chord,
      aux_sym_content_line_repeat1,
    STATE(3), 5,
      sym__line,
      sym_delegate_block,
      sym_directive,
      sym_content_line,
      aux_sym_source_file_repeat1,
  [31] = 8,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(22), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(28), 1,
      sym_lyrics,
    STATE(16), 1,
      sym_block_start_directive,
    ACTIONS(19), 2,
      sym__empty_line,
      sym_comment,
    STATE(4), 2,
      sym_chord,
      aux_sym_content_line_repeat1,
    STATE(3), 5,
      sym__line,
      sym_delegate_block,
      sym_directive,
      sym_content_line,
      aux_sym_source_file_repeat1,
  [62] = 6,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_LF,
    ACTIONS(37), 1,
      sym_lyrics,
    STATE(5), 2,
      sym_chord,
      aux_sym_content_line_repeat1,
    ACTIONS(33), 3,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
  [84] = 5,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_LBRACK,
    ACTIONS(46), 1,
      sym_lyrics,
    STATE(5), 2,
      sym_chord,
      aux_sym_content_line_repeat1,
    ACTIONS(41), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LF,
  [104] = 3,
    ACTIONS(53), 1,
      anon_sym_LF,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(51), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [118] = 2,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(57), 5,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LF,
      anon_sym_LBRACK,
  [130] = 3,
    ACTIONS(63), 1,
      anon_sym_LF,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(61), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [144] = 3,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(67), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [158] = 2,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(73), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [169] = 2,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(77), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [180] = 2,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(81), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [191] = 2,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(85), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [202] = 2,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(89), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [213] = 2,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(93), 4,
      sym__empty_line,
      sym_comment,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [224] = 5,
    ACTIONS(95), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      aux_sym_block_content_token1,
    STATE(11), 1,
      sym_block_end_directive,
    STATE(17), 1,
      aux_sym_block_content_repeat1,
    STATE(22), 1,
      sym_block_content,
  [240] = 3,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(101), 1,
      aux_sym_block_content_token1,
    STATE(19), 1,
      aux_sym_block_content_repeat1,
  [250] = 3,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(105), 1,
      anon_sym_LF,
    ACTIONS(107), 1,
      aux_sym_block_content_token1,
  [260] = 3,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      aux_sym_block_content_token1,
    STATE(19), 1,
      aux_sym_block_content_repeat1,
  [270] = 3,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_LF,
    ACTIONS(118), 1,
      aux_sym_block_content_token1,
  [280] = 2,
    ACTIONS(120), 1,
      aux_sym_block_start_directive_token1,
    ACTIONS(122), 1,
      sym_directive_name,
  [287] = 2,
    ACTIONS(95), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_block_end_directive,
  [294] = 2,
    ACTIONS(124), 1,
      aux_sym_block_start_directive_token2,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
  [301] = 2,
    ACTIONS(128), 1,
      aux_sym_block_start_directive_token2,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
  [308] = 1,
    ACTIONS(132), 2,
      anon_sym_LBRACE,
      aux_sym_block_content_token1,
  [313] = 1,
    ACTIONS(134), 2,
      anon_sym_LBRACE,
      aux_sym_block_content_token1,
  [318] = 1,
    ACTIONS(136), 1,
      aux_sym_block_end_directive_token1,
  [322] = 1,
    ACTIONS(138), 1,
      sym_directive_value,
  [326] = 1,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
  [330] = 1,
    ACTIONS(142), 1,
      sym_directive_value,
  [334] = 1,
    ACTIONS(144), 1,
      sym_chord_name,
  [338] = 1,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
  [342] = 1,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
  [346] = 1,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
  [350] = 1,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 104,
  [SMALL_STATE(7)] = 118,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 144,
  [SMALL_STATE(10)] = 158,
  [SMALL_STATE(11)] = 169,
  [SMALL_STATE(12)] = 180,
  [SMALL_STATE(13)] = 191,
  [SMALL_STATE(14)] = 202,
  [SMALL_STATE(15)] = 213,
  [SMALL_STATE(16)] = 224,
  [SMALL_STATE(17)] = 240,
  [SMALL_STATE(18)] = 250,
  [SMALL_STATE(19)] = 260,
  [SMALL_STATE(20)] = 270,
  [SMALL_STATE(21)] = 280,
  [SMALL_STATE(22)] = 287,
  [SMALL_STATE(23)] = 294,
  [SMALL_STATE(24)] = 301,
  [SMALL_STATE(25)] = 308,
  [SMALL_STATE(26)] = 313,
  [SMALL_STATE(27)] = 318,
  [SMALL_STATE(28)] = 322,
  [SMALL_STATE(29)] = 326,
  [SMALL_STATE(30)] = 330,
  [SMALL_STATE(31)] = 334,
  [SMALL_STATE(32)] = 338,
  [SMALL_STATE(33)] = 342,
  [SMALL_STATE(34)] = 346,
  [SMALL_STATE(35)] = 350,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_line, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end_directive, 3, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end_directive, 3, 0, 1),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 5, 0, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 5, 0, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_line, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delegate_block, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delegate_block, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 6, 0, 2),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 6, 0, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delegate_block, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delegate_block, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end_directive, 4, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end_directive, 4, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4, 0, 1),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 4, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_content, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_directive, 3, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_directive, 3, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_content_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_content_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_directive, 5, 0, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_directive, 5, 0, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_directive, 4, 0, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_directive, 6, 0, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [140] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_chordpro(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "chordpro",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
