/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__empty_line = 1,
  anon_sym_LBRACE = 2,
  aux_sym_block_start_directive_token1 = 3,
  aux_sym_block_start_directive_token2 = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LF = 6,
  aux_sym_block_end_directive_token1 = 7,
  aux_sym_block_content_token1 = 8,
  sym_directive_name = 9,
  sym_directive_value = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_chord_name = 13,
  sym_lyrics = 14,
  sym_comment = 15,
  sym_source_file = 16,
  sym__line = 17,
  sym_delegate_block = 18,
  sym_block_start_directive = 19,
  sym_block_end_directive = 20,
  sym_block_content = 21,
  sym_directive = 22,
  sym_content_line = 23,
  sym_chord = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_block_content_repeat1 = 26,
  aux_sym_content_line_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__empty_line] = "_empty_line",
  [anon_sym_LBRACE] = "{",
  [aux_sym_block_start_directive_token1] = "directive_name",
  [aux_sym_block_start_directive_token2] = "block_start_directive_token2",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LF] = "\n",
  [aux_sym_block_end_directive_token1] = "directive_name",
  [aux_sym_block_content_token1] = "block_content_token1",
  [sym_directive_name] = "directive_name",
  [sym_directive_value] = "directive_value",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_chord_name] = "chord_name",
  [sym_lyrics] = "lyrics",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_delegate_block] = "delegate_block",
  [sym_block_start_directive] = "block_start_directive",
  [sym_block_end_directive] = "block_end_directive",
  [sym_block_content] = "block_content",
  [sym_directive] = "directive",
  [sym_content_line] = "content_line",
  [sym_chord] = "chord",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_content_repeat1] = "block_content_repeat1",
  [aux_sym_content_line_repeat1] = "content_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__empty_line] = sym__empty_line,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_block_start_directive_token1] = sym_directive_name,
  [aux_sym_block_start_directive_token2] = aux_sym_block_start_directive_token2,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_block_end_directive_token1] = sym_directive_name,
  [aux_sym_block_content_token1] = aux_sym_block_content_token1,
  [sym_directive_name] = sym_directive_name,
  [sym_directive_value] = sym_directive_value,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_chord_name] = sym_chord_name,
  [sym_lyrics] = sym_lyrics,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_delegate_block] = sym_delegate_block,
  [sym_block_start_directive] = sym_block_start_directive,
  [sym_block_end_directive] = sym_block_end_directive,
  [sym_block_content] = sym_block_content,
  [sym_directive] = sym_directive,
  [sym_content_line] = sym_content_line,
  [sym_chord] = sym_chord,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_content_repeat1] = aux_sym_block_content_repeat1,
  [aux_sym_content_line_repeat1] = aux_sym_content_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__empty_line] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_start_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_start_directive_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_end_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_chord_name] = {
    .visible = true,
    .named = true,
  },
  [sym_lyrics] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_delegate_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_start_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_block_end_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_chord] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') SKIP(15);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == 's') ADVANCE(39);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead == ' ' ||
          lookahead == ':') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\r') SKIP(4);
      if (lookahead == 's') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == '\r') SKIP(5);
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '\r') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == '\r') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(49);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == '_') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 14:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 15:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') SKIP(15);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == 's') ADVANCE(39);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(50);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(50);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__empty_line);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_block_start_directive_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_block_start_directive_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_block_end_directive_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_block_content_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '_') ADVANCE(36);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '_') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'a') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'd') ADVANCE(27);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'n') ADVANCE(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'o') ADVANCE(33);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'o') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 'r') ADVANCE(40);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == 't') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_directive_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_directive_value);
      if (lookahead == '\r') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_directive_value);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_chord_name);
      if (lookahead == '\r') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_chord_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_lyrics);
      if (lookahead == '\r') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_lyrics);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 17, .external_lex_state = 1},
  [2] = {.lex_state = 17, .external_lex_state = 1},
  [3] = {.lex_state = 17, .external_lex_state = 1},
  [4] = {.lex_state = 16, .external_lex_state = 1},
  [5] = {.lex_state = 16, .external_lex_state = 1},
  [6] = {.lex_state = 16, .external_lex_state = 1},
  [7] = {.lex_state = 16, .external_lex_state = 1},
  [8] = {.lex_state = 16, .external_lex_state = 1},
  [9] = {.lex_state = 16, .external_lex_state = 1},
  [10] = {.lex_state = 17, .external_lex_state = 1},
  [11] = {.lex_state = 17, .external_lex_state = 1},
  [12] = {.lex_state = 17, .external_lex_state = 1},
  [13] = {.lex_state = 17, .external_lex_state = 1},
  [14] = {.lex_state = 17, .external_lex_state = 1},
  [15] = {.lex_state = 17, .external_lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__empty_line] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [aux_sym_block_start_directive_token1] = ACTIONS(1),
    [aux_sym_block_start_directive_token2] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_block_end_directive_token1] = ACTIONS(1),
    [sym_directive_name] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym__line] = STATE(2),
    [sym_delegate_block] = STATE(2),
    [sym_block_start_directive] = STATE(16),
    [sym_directive] = STATE(2),
    [sym_content_line] = STATE(2),
    [sym_chord] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_content_line_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__empty_line] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_lyrics] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_lyrics,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym__empty_line,
    ACTIONS(19), 1,
      sym_comment,
    STATE(16), 1,
      sym_block_start_directive,
    STATE(4), 2,
      sym_chord,
      aux_sym_content_line_repeat1,
    STATE(3), 5,
      sym__line,
      sym_delegate_block,
      sym_directive,
      sym_content_line,
      aux_sym_source_file_repeat1,
  [33] = 9,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym__empty_line,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      sym_lyrics,
    ACTIONS(35), 1,
      sym_comment,
    STATE(16), 1,
      sym_block_start_directive,
    STATE(4), 2,
      sym_chord,
      aux_sym_content_line_repeat1,
    STATE(3), 5,
      sym__line,
      sym_delegate_block,
      sym_directive,
      sym_content_line,
      aux_sym_source_file_repeat1,
  [66] = 6,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      anon_sym_LF,
    ACTIONS(44), 1,
      sym_lyrics,
    ACTIONS(38), 2,
      sym_comment,
      ts_builtin_sym_end,
    ACTIONS(40), 2,
      sym__empty_line,
      anon_sym_LBRACE,
    STATE(5), 2,
      sym_chord,
      aux_sym_content_line_repeat1,
  [88] = 5,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      sym_lyrics,
    ACTIONS(46), 2,
      sym_comment,
      ts_builtin_sym_end,
    STATE(5), 2,
      sym_chord,
      aux_sym_content_line_repeat1,
    ACTIONS(48), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LF,
  [108] = 3,
    ACTIONS(60), 1,
      anon_sym_LF,
    ACTIONS(56), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(58), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [122] = 2,
    ACTIONS(62), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(64), 4,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LF,
      anon_sym_LBRACK,
  [134] = 3,
    ACTIONS(70), 1,
      anon_sym_LF,
    ACTIONS(66), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(68), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [148] = 3,
    ACTIONS(76), 1,
      anon_sym_LF,
    ACTIONS(72), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(74), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [162] = 2,
    ACTIONS(78), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(80), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [173] = 2,
    ACTIONS(82), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(84), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [184] = 2,
    ACTIONS(86), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(88), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [195] = 2,
    ACTIONS(90), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(92), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [206] = 2,
    ACTIONS(94), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(96), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [217] = 2,
    ACTIONS(98), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_lyrics,
    ACTIONS(100), 3,
      sym__empty_line,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [228] = 5,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      aux_sym_block_content_token1,
    STATE(11), 1,
      sym_block_end_directive,
    STATE(17), 1,
      aux_sym_block_content_repeat1,
    STATE(22), 1,
      sym_block_content,
  [244] = 3,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      aux_sym_block_content_token1,
    STATE(19), 1,
      aux_sym_block_content_repeat1,
  [254] = 3,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(112), 1,
      anon_sym_LF,
    ACTIONS(114), 1,
      aux_sym_block_content_token1,
  [264] = 3,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      aux_sym_block_content_token1,
    STATE(19), 1,
      aux_sym_block_content_repeat1,
  [274] = 3,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 1,
      anon_sym_LF,
    ACTIONS(125), 1,
      aux_sym_block_content_token1,
  [284] = 2,
    ACTIONS(127), 1,
      aux_sym_block_start_directive_token1,
    ACTIONS(129), 1,
      sym_directive_name,
  [291] = 2,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_block_end_directive,
  [298] = 2,
    ACTIONS(131), 1,
      aux_sym_block_start_directive_token2,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
  [305] = 2,
    ACTIONS(135), 1,
      aux_sym_block_start_directive_token2,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
  [312] = 1,
    ACTIONS(139), 2,
      anon_sym_LBRACE,
      aux_sym_block_content_token1,
  [317] = 1,
    ACTIONS(141), 2,
      anon_sym_LBRACE,
      aux_sym_block_content_token1,
  [322] = 1,
    ACTIONS(143), 1,
      aux_sym_block_end_directive_token1,
  [326] = 1,
    ACTIONS(145), 1,
      sym_directive_value,
  [330] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [334] = 1,
    ACTIONS(149), 1,
      sym_directive_value,
  [338] = 1,
    ACTIONS(151), 1,
      sym_chord_name,
  [342] = 1,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
  [346] = 1,
    ACTIONS(155), 1,
      anon_sym_RBRACK,
  [350] = 1,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
  [354] = 1,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 88,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 122,
  [SMALL_STATE(8)] = 134,
  [SMALL_STATE(9)] = 148,
  [SMALL_STATE(10)] = 162,
  [SMALL_STATE(11)] = 173,
  [SMALL_STATE(12)] = 184,
  [SMALL_STATE(13)] = 195,
  [SMALL_STATE(14)] = 206,
  [SMALL_STATE(15)] = 217,
  [SMALL_STATE(16)] = 228,
  [SMALL_STATE(17)] = 244,
  [SMALL_STATE(18)] = 254,
  [SMALL_STATE(19)] = 264,
  [SMALL_STATE(20)] = 274,
  [SMALL_STATE(21)] = 284,
  [SMALL_STATE(22)] = 291,
  [SMALL_STATE(23)] = 298,
  [SMALL_STATE(24)] = 305,
  [SMALL_STATE(25)] = 312,
  [SMALL_STATE(26)] = 317,
  [SMALL_STATE(27)] = 322,
  [SMALL_STATE(28)] = 326,
  [SMALL_STATE(29)] = 330,
  [SMALL_STATE(30)] = 334,
  [SMALL_STATE(31)] = 338,
  [SMALL_STATE(32)] = 342,
  [SMALL_STATE(33)] = 346,
  [SMALL_STATE(34)] = 350,
  [SMALL_STATE(35)] = 354,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_line, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end_directive, 3, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end_directive, 3, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 5, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 5, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_line, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delegate_block, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delegate_block, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 6, 0, 2),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 6, 0, 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delegate_block, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delegate_block, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end_directive, 4, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end_directive, 4, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 4, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_content, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_directive, 3, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_directive, 3, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_content_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_content_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_directive, 5, 0, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_directive, 5, 0, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_directive, 4, 0, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_directive, 6, 0, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [147] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_comment = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_chordpro_external_scanner_create(void);
void tree_sitter_chordpro_external_scanner_destroy(void *);
bool tree_sitter_chordpro_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_chordpro_external_scanner_serialize(void *, char *);
void tree_sitter_chordpro_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_chordpro(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_chordpro_external_scanner_create,
      tree_sitter_chordpro_external_scanner_destroy,
      tree_sitter_chordpro_external_scanner_scan,
      tree_sitter_chordpro_external_scanner_serialize,
      tree_sitter_chordpro_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "chordpro",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
