// @chordsketch/node — platform resolver for the napi-rs native addon.
//
// Loads the right per-platform prebuilt binary package at runtime, matching
// the napi-rs multi-package convention. The five platform packages declared
// in `optionalDependencies` of package.json cover every target in the
// `napi.targets` list of this package's manifest:
//
//   - @chordsketch/node-linux-x64-gnu       (linux x64)
//   - @chordsketch/node-linux-arm64-gnu     (linux arm64)
//   - @chordsketch/node-darwin-x64          (macOS x64)
//   - @chordsketch/node-darwin-arm64        (macOS arm64 / Apple Silicon)
//   - @chordsketch/node-win32-x64-msvc      (Windows x64)
//
// If you see "Unsupported platform" from this file, either the runtime
// platform is not in the supported list (add a new target to napi.targets,
// build + publish a prebuilt package, and extend this resolver) OR the
// right optional dependency failed to install (check npm's error output
// for the optional dep that was skipped).
//
// This file is committed deliberately rather than generated by `napi build`
// so the publish job does not have to run the Rust build — it only needs
// to move each platform's .node artifact into its platform subdirectory
// under `npm/` before running `npm publish`. See docs/releasing.md for the
// full flow.

const { platform, arch } = process;

let nativeBinding = null;
let loadErrors = [];

function tryLoad(pkg) {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require(pkg);
  } catch (err) {
    loadErrors.push({ pkg, err });
    return null;
  }
}

switch (platform) {
  case 'linux':
    if (arch === 'x64') {
      nativeBinding = tryLoad('@chordsketch/node-linux-x64-gnu');
    } else if (arch === 'arm64') {
      nativeBinding = tryLoad('@chordsketch/node-linux-arm64-gnu');
    }
    break;

  case 'darwin':
    if (arch === 'x64') {
      nativeBinding = tryLoad('@chordsketch/node-darwin-x64');
    } else if (arch === 'arm64') {
      nativeBinding = tryLoad('@chordsketch/node-darwin-arm64');
    }
    break;

  case 'win32':
    if (arch === 'x64') {
      nativeBinding = tryLoad('@chordsketch/node-win32-x64-msvc');
    }
    break;
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    // A matching platform package exists in optionalDependencies but failed
    // to load. Surface the first load error so the user sees the actual
    // require() failure rather than a generic "unsupported platform".
    const { pkg, err } = loadErrors[0];
    const reason = err && err.message ? err.message : String(err);
    throw new Error(
      `Failed to load @chordsketch/node: native binding ${pkg} is installed ` +
        `but could not be loaded (${reason}). This usually means the ` +
        `optional dependency failed to install cleanly; try reinstalling ` +
        `with \`npm install --force @chordsketch/node\`.`,
    );
  }
  throw new Error(
    `Unsupported platform: ${platform} ${arch}. ` +
      `@chordsketch/node ships prebuilt binaries for linux/darwin (x64, arm64) ` +
      `and win32 x64; other targets must build from source via ` +
      `\`cargo build --release -p chordsketch-napi\`.`,
  );
}

module.exports = nativeBinding;
module.exports.default = nativeBinding;
