name: zz-tmp-caller
on:
  push:
    branches: [ci/release-call-graph]
    paths: [".github/workflows/zz-tmp-caller.yml"]
jobs:
  expect-true:
    uses: ./.github/workflows/zz-tmp-callee.yml
    with:
      flag: ${{ github.event_name == 'push' }}
  expect-false:
    uses: ./.github/workflows/zz-tmp-callee.yml
    with:
      flag: ${{ github.event_name == 'workflow_dispatch' }}
